# Enable AndroidX and Jetifier
android.useAndroidX=true
android.enableJetifier=true

# Kotlin Code Style (if Kotlin is used)
kotlin.code.style=official

# Gradle Daemon and JVM Memory Settings
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true